# -*- coding: utf-8 -*-
"""Rock Paper Scissor Game Deploy

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10pu0e9fho88KPAvQy-ROcI6sZx2e15bK
"""

import streamlit as st
import random

# Dictionary setup
yourDict = {"R": -1, "P": 0, "S": 1}
reverseDict = {-1: "Rock", 0: "Paper", 1: "Scissor"}

st.title("🪨📄✂️ Rock Paper Scissor Game")
st.markdown("#### Choose your option below:")

# Streamlit input
your_choice = st.radio("Your Move:", options=["R", "P", "S"], index=0, horizontal=True)

# Play button
if st.button("Play!"):
    Abs = random.choice([-1, 0, 1])  # Computer choice
    you = yourDict[your_choice]

    st.write(f"🧑 You chose: **{reverseDict[you]}**")
    st.write(f"🤖 Abs chose: **{reverseDict[Abs]}**")

    if Abs == you:
        st.info("It's a Draw! Try Again.")
    else:
        if Abs == 1 and you == 0:
            st.error("✂️ Scissor cuts Paper. You Lose! Abs Wins!")
        elif Abs == 1 and you == -1:
            st.success("🪨 Rock crushes Scissor. You Win!")
        elif Abs == 0 and you == 1:
            st.success("✂️ Scissor cuts Paper. You Win!")
        elif Abs == 0 and you == -1:
            st.error("📄 Paper wraps Rock. You Lose! Abs Wins!")
        elif Abs == -1 and you == 1:
            st.error("🪨 Rock crushes Scissor. You Lose! Abs Wins!")
        elif Abs == -1 and you == 0:
            st.success("📄 Paper wraps Rock. You Win!")